### ISSUE TITLE
Automatically determine the platform information and generate a 'platform.json' file when installing the tools

### ISSUE THREAD

**Issue by elavoie** [Sable/wu-wei-benchmarking-toolkit#13]
The '.wu/setup.json' description file's 'platform' property should be automatically updated with the platform short-name of the current platform.

**Comment by wukefe** [comment]
Add a new file, `pinfo.py`, under `bin/` directory.  It is not required to install additional python packages before you run it.

``` python
python pinfo.py
```

Its output can be saved in `platform/` for the purpose of further configuration.

**Comment by elavoie** [comment]
@wukefe could you do a pull request with your new script?

**Comment by wukefe** [comment]
@elavoie Because there is only one file added into the project, I cloned the project, added the new file and pushed the latest commit.  Please check the latest commit.  Next time, when I add some benchmarks, I will create a pull request.

**Comment by elavoie** [comment]
That's perfect. Now from your cloned repository interface, click on the pull request tab, and ask to merge into Sable/wu-wei-benchmarking-toolkit master branch.

**Comment by elavoie** [comment]
Oh I see, you actually committed directly to master. That's fine, next time do a pull request so I can review the changes before they land in master.

**Comment by wukefe** [comment]
@elavoie Sure.  I actually realized the case that I needed to create a new branch before I sent a pull request to merge two branches.  But I strictly followed the online instructions which mislead me.   Next time would be fine.

**Comment by elavoie** [comment]
Well that's one way. The other one is to fork the repo in your own personal account, work from that master branch, and then do a pull request from there.

**Comment by wukefe** [comment]
I think I have figured out the way you suggest.  Please take a look at the latest pull request.  It is easier for me to add new changes in a forked repo.  Then, you will supervise the update on the master branch.   Thanks.

**Comment by elavoie** [comment]
The platform is now determined automatically when a benchmark is run from the installed platforms. If none match the current platform, a new one is created and the short-name is obtained from the user.
