### ISSUE TITLE
Compiler none-matlab should copy rather than cat

### ISSUE THREAD

**Issue by gnuvince** [Sable/wu-wei-benchmarking-toolkit#27]
Some MATLAB benchmarks have multiple files and, in true MATLAB fashion, some use the keyword `end` to terminate the function while others don't.  When these functions are catted into a single file, MATLAB reports an error that if a single `.m` file contains multiple functions, they should all be `end`-terminated.

I suggest we "compile" MATLAB files by copying all the files into the build directory rather than catting them together in a single file.

**Comment by gnuvince** [comment]
Laurie confirms that we should copy rather than cat; the file system structure has meaning in the lookup of functions in Matlab (e.g. functions in `private/` directory).

**Comment by elavoie** [comment]
Moved issue to Sable/Ostrich2#89
