### ISSUE TITLE
There should be a command/option to go from benchmark to build id

### ISSUE THREAD

**Issue by gnuvince** [Sable/wu-wei-benchmarking-toolkit#29]
I was trying to view the generated code for a benchmark and finding the correct directory in the `builds` directory could only be done with grepping.  Should there not be a command (or option to an existing command) to get this mapping?  For example:

```
$ wu list --build-dir bubble matjuice
/home/sable/vfoley1/workspace/Ostrich2/builds/af25b6e3dd023fa634771e5eaec2f64b6093b18e
```

**Comment by elavoie** [comment]
You can do 'wu build -v' to have the verbose version that tells you the build directory. Is should always be the same.
